### PR TITLE
feat(ci): release on tag 👷

### PR DESCRIPTION
**Pull request by meysam81**
You can see the ultimate result in the screenshots below. However, this will remove your ability to release on the marketplace. But the upside is that all you have to do is to push a tag starting with `v`, and everything else is taken care of.

image

Screenshot from 2023-08-10 19-06-53

Screenshot from 2023-08-10 19-08-20

### CODE REVIEW

**Comment by nicolaiunrein** [comment]
I struggle to see the real benefits from publishing the action to the marketplace. The only reason I could think of is discoverability. But I mostly copy/paste/alter workflows from well maintained high quality crates which has always been enough for my needs and I have never really looked for actions on the marketplace. Why would we loose the ability to publish to the marketplace if we decided to merge your PR?

**Comment by meysam81** [comment]
You wouldn't "lose" it in the literal sense of the word, but rather it won't be published to the marketplace if you don't release it from [GitHub Release page](https://github.com/nicolaiunrein/cargo-get/releases/new). The only benefit there is when publishing to marketplace is better reach and recognition, but it is still usable if someone has a step `uses: nicolaiunrein/cargo-get` in their workflows ([example](https://github.com/nicolaiunrein/cargo-get/blob/8ad2b01b5ae4099470f6f83551a770bbf28fd3b8/.github/workflows/github-actions.yml#L28), [example2](https://github.com/vlad-onis/twir_parser/pull/41)).

It is however able to do a new GitHub Release on [every push of the tags starting with `v`](https://github.com/nicolaiunrein/cargo-get/blob/f2853da521da35ee3376ab1000e1ff4afb9ca3a6/.github/workflows/release.yml#L10).

**Comment by nicolaiunrein** [comment]
I am still uncertain what to do. [here](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#about-publishing-actions) it says that repos for actions on the marketplace are not allowed to have any workflow files.

**Comment by meysam81** [comment]
"_GitHub Actions cannot have any workflow files_" has never stopped me publishing to the marketplace before: [example](https://github.com/licenseware/send-email-notification)

**Pull request merged**
